### ISSUE TITLE
page refresh on first uploaded entity on map

### ISSUE THREAD

**Issue by IOZD** [articodeltd/angular-cesium#130]
when you upload a uc-entity to the map there is a black page refresh that catches the eye.

**Comment by eitanfr** [comment]
Can you add the code you are trying to run?

**Comment by IOZD** [comment]
this.circles$ = Observable.create((observer) => {
      this.cesiumService.cesiumEntityNotification
        .subscribe((acNotification: AcNotification) => {
          if (acNotification.entity instanceof OmnCesiumCircle) {
            observer.next(acNotification);
          }
        });
    });

**Comment by eitanfr** [comment]
@IOZD the code seems fine, can you show the html template? 
strange, does it happen all the time? on updates? on creation?
