### ISSUE TITLE
Cesium Full Screen makes entire page full screen, not cesium container

### ISSUE THREAD

**Issue by CHBaker** [articodeltd/angular-cesium#158]
I currently have cesium in a div about half the size of my page, and when I click full screen it makes the background black, the whole html page goes full screen, and cesium stays the same size.

could this be related to [this issue](https://github.com/AnalyticalGraphicsInc/cesium-google-earth-examples/issues/7)?

-----UPDATE--------

could it be related to my css styles?
```
#cesiumContainer {
    width: 100%;
    height: 720px;
    margin: 0; padding: 0;
    overflow: hidden;
}

.map-container {
    height: 720px;
    box-shadow: 4px 4px 7px #d2d2d2;
}

```

and then having `ViewEncapsulation.None`?

**Comment by eitanfr** [comment]
maybe you can try making full screen button yourself and do:

```typescript
onClick(){
const viewer = this.mapsManagerService.getMap().getCesiumViewer();
viewer.canvas.requestFullscreen() // for chrome do viewer.canvaswebkitRequestFulscreen()
}
```

**Comment by CHBaker** [comment]
hm. okay, how could I opt for both? I'm not positive which browser a user will be on.

**Comment by eitanfr** [comment]
check out the prefix table in [MDN FullscreenApi](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API).
And do:

```typescript
if (''webkitRequestFulscreen' in canvas) {
   canvas.webkitRequestFulscreen();
} else if ('requestFulscreen' in canvas) {
   canvas.requestFulscreen();
} // same for other browsers prefixes 
```

Not sure about the css values you showed, try changing it.
But `requestFulscreen()` API worked for me in a recent project I did .

**Comment by CHBaker** [comment]
The code above seemed to work alright for me, it went into full screen. the problem is, it didn't widen the viewer, or display my menu or the built in cesium tool bar

![screenshot from 2017-11-09 08-28-27](https://user-images.githubusercontent.com/14304935/32613443-2629cfa0-c528-11e7-815b-29bf292a0168.png)

**Comment by eitanfr** [comment]
you always can do requestFullScreen on the document :)

**Comment by CHBaker** [comment]
you mean, my entire page? Wouldn't that just make my webpage full screen and the cesium viewer still partial?

**Comment by eitanfr** [comment]
Try it out... Not sure if i understand your needs, if you only want to control cesium globe size you can change the camera zoom.

**Comment by CHBaker** [comment]
So, to clarify, if you look at the screenshot above all the widgets disappear, and the actual cesium window is not that large, it is cut off by straight black. I'm trying to make cesium take up the whole screen and the widgets to show, like a normal full screen cesium feature.

**Comment by CHBaker** [comment]
any more ideas? could you maybe send me a working example, where the Cesium window is inside a a bootstrap container like this: 
 `<container><row><col>cesium</col></row></container>`

**Comment by bampakoa** [comment]
@CHBaker is this still an issue? I would love to help in that case :smiley:

**Comment by CHBaker** [comment]
@bampakoa yes! it is still an issue, I haven't made any progress on it because I have switch projects for the time being, but I still haven't been able to make it work

**Comment by bampakoa** [comment]
@CHBaker can you try to alter the styles runtime, when clicking the fullscreen button? For example, if you set it as described in the README:

```
html, body, #cesiumContainer {
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
    overflow: hidden;
}
```

it should work

**Comment by devondanpearce** [comment]
Experienced this. Turned out I'd not set the fullscreenElement on the viewer to the ID of my container. If you don't set this, it defaults to document.body which full screens the whole page (see https://cesium.com/docs/cesiumjs-ref-doc/Viewer.html).

**Comment by crane168** [comment]
> 经历了这一点。原来，我没有将查看器上的fullscreenElement设置为容器的ID。如果未设置，则默认为document.body，它会全屏显示整个页面（请参阅https://cesium.com/docs/cesiumjs-ref-doc/Viewer.html）。
You're right,it has resolve my question,thank you!
