### ISSUE TITLE
WebGl Heat Map the Angular Way

### ISSUE THREAD

**Issue by CHBaker** [articodeltd/angular-cesium#162]
Hello,

I'm trying to get a data stream to flow for a heatmap by following the cesium.js heatmap population tutorial [here](http://50.250.145.136:8080/Apps/Sandcastle/?src=Custom%20DataSource.html&label=DataSources). But I'm running into a lot of problems trying to right the getter setter functions for the webGL prototype object. Is there a syntax for this in typescript? Or a better api to use for these?

I only found 4 results on google when searching for this issue :/

**Comment by eitanfr** [comment]
sorry, I don't know about any official typing for cesium and webgl properties.

you can try this project that generates cesium typings from the official doc (I never got to try it myself).

**Comment by CHBaker** [comment]
seems like you forgot the link @eitanfr, I'm not sure this is a typing issue? I just can't figure out how to do a typescript syntax of the getter setter object, i.e.

```
Object.defineProperties(WebGLGlobeDataSource.prototype, {
    name : {
        get : function() {
            return this._name;
        }
    },
    clock : {
        value : undefined,
        writable : false
    },
...
```

**Comment by eitanfr** [comment]
sorry,here are the links:
https://github.com/s-innovations/S-Innovations.Cesium
also this one: https://github.com/beginor/cesium-typings.

about the syntax, you can write plain old javascript in typescript (if you have typings erros just declare your object as any)
