### ISSUE TITLE
A Problem

### ISSUE THREAD

**Issue by z3214965** [articodeltd/angular-cesium#166]
hi,
I have a problem about event priority，now I have two left click event， set priority 1 and 2，but when I click Nothing happened，what should I do？

**Comment by eitanfr** [comment]
can you please add a code sample?

**Comment by z3214965** [comment]
![first](https://user-images.githubusercontent.com/18589356/32610010-73fc071a-c59c-11e7-95cd-409f45da50c6.PNG)
first event
![two](https://user-images.githubusercontent.com/18589356/32610035-82c69864-c59c-11e7-9413-d0053c96b7d4.PNG)
second event
if I not set priority，I can use "ac-point-desc" creat a point，but set priority Nothing happened

**Comment by z3214965** [comment]
I want to select the object from the first event before clicking on the second one

**Comment by eitanfr** [comment]
hi, there is a good example of event priority [here](https://github.com/TGFTech/angular-cesium/blob/master/demo/app/components/event-test-layer/event-test-layer.component.ts).
you can try clone our project and play with our demo....

on the first event you filter entites with type of AcEntity, does the entities you display are of type AcEntity? maybe this is the problem

**Comment by z3214965** [comment]
I mean, I have two left_click events, when I set the priority, the high priority is first penalized and the low priority is the penalty, but not the high priority, the low priority is not triggered
