### ISSUE TITLE
TSC errors for implicit any

### ISSUE THREAD

**Issue by brian428** [articodeltd/angular-cesium#170]
Just FYI, there are several warnings from TSC when no-implicit-any is enabled:

node_modules\angular-cesium\src\angular-cesium-widgets\directives\draggable-to-map.directive.d.ts
Error:(7, 9) TS7008: Member 'style' implicitly has an 'any' type.

node_modules\angular-cesium\src\angular-cesium\components\ac-array-desc\ac-array-desc.component.d.ts
Error:(10, 16) TS7006: Parameter 'item' implicitly has an 'any' type.
Error:(10, 22) TS7006: Parameter 'index' implicitly has an 'any' type.

node_modules\angular-cesium\src\angular-cesium\services\ac-html-manager\ac-html-manager.service.d.ts
Error:(6, 9) TS7008: Member 'entity' implicitly has an 'any' type.
Error:(7, 9) TS7008: Member 'primitive' implicitly has an 'any' type.
Error:(10, 9) TS7008: Member 'entity' implicitly has an 'any' type.
Error:(11, 9) TS7008: Member 'primitive' implicitly has an 'any' type.

node_modules\angular-cesium\src\angular-cesium\services\coordinate-converter\coordinate-converter.service.d.ts
Error:(27, 9) TS7008: Member 'latitude' implicitly has an 'any' type.
Error:(28, 9) TS7008: Member 'longitude' implicitly has an 'any' type.
Error:(30, 9) TS7008: Member 'latitude' implicitly has an 'any' type.
Error:(31, 9) TS7008: Member 'longitude' implicitly has an 'any' type.
Error:(35, 9) TS7008: Member 'latitude' implicitly has an 'any' type.
Error:(36, 9) TS7008: Member 'longitude' implicitly has an 'any' type.
Error:(38, 9) TS7008: Member 'latitude' implicitly has an 'any' type.
Error:(39, 9) TS7008: Member 'longitude' implicitly has an 'any' type.

**Comment by eitanfr** [comment]
Indeed our project is with `noImplicitAny: false`. 
thx for mention it , we will fix all the above soon...
