### ISSUE TITLE
missing images in Production

### ISSUE THREAD

**Issue by CHBaker** [articodeltd/angular-cesium#176]
**Intended outcome:**
images load in the Cesium container

**Actual outcome:**
missing resource thumbnails

**How to reproduce the issue:**
run `ng build --prod --aot`

**Version**
0.0.25

![cesium](https://user-images.githubusercontent.com/14304935/33290501-1a11d3a0-d380-11e7-80ea-64d10f4ad339.png)

**Comment by eitanfr** [comment]
Never had a chance to use cesium widgets in my app... But did check if the image resources served properly by your app?

**Comment by CHBaker** [comment]
hmmm. this is a new problem for me, I read that I need to put  the images in the asset's section of my cli file, I'll just need to figure out how to structure that, and test it out. I'll get back to you
