### ISSUE TITLE
ac-primitive-polyline

### ISSUE THREAD

**Issue by dorperetz** [articodeltd/angular-cesium#178]
hey,

there is no primitive single (not as part of a layer) polyline option,
ive looked at it , as you suggested its just changing the drawer from polylinedrawer to primitive polyline drawer ,but couldnt test it.

ill be super glad to have an 'ac-primitive-polyline' component.
Thanks !

**Comment by hodbauer** [comment]
maybe that?
[ac-polyline-primitive-desc](https://github.com/articodeltd/angular-cesium/tree/master/src/angular-cesium/components/ac-polyline-primitive-desc)
