### ISSUE TITLE
In Angular 5, Getting Started instructions don't work

### ISSUE THREAD

**Issue by breynolds** [articodeltd/angular-cesium#181]
I followed the steps in getting started, but the app doesn't work. Looking at the console there's an error that says "Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'." Looks like ngx-charts has the same issue. ngOutletContext was deprecated in an earlier version of Angular, and it's no longer in Angular 5. 

**Intended outcome:**
Sample app starts up

**Actual outcome:**
"ng serve" compiles fine, but I get a runtime error in the console after loading the page

**How to reproduce the issue:**
Follow the getting started steps 

**Version**
angular-cesium 0.0.36
cesium 1.40
angular: 5.0.0

**Comment by eitanfr** [comment]
hi , angular 5, `ngOutletContext` was fixed in the last version. but support to angular 5 still wasnt tested . 
follow #127

**Comment by schitzN** [comment]
ngOutletContext was removed in angular 5 and is now called ngTemplateOutletContext.

You could fix this by yourself by changing this in ac-html-desc.component.ts but this is not recommended and should be fixed asap!

**Comment by eitanfr** [comment]
I will explain myself better, in version 0.0.37 `ngOutletContext` changed to `ngTemplateOutletContext` but still wasn't tested with angular 5.

**Comment by davidyaha** [comment]
Was fixed ages ago
