### ISSUE TITLE
Availability property of entity does not work

### ISSUE THREAD

**Issue by jhaughe1** [articodeltd/angular-cesium#187]
**Intended outcome:**
Use availability property of an entity (ex. have am ac-box-desc only show when available). 

**Actual outcome:**
Availability property of entity is not supported. 

**How to reproduce the issue:**

HTML:

<ac-layer acFor="let ev of eventsCesium" [context]="this" [show]="show" [store]="store">

	<ac-box-desc props="{
		dimensions: ev.box.dimensions,
		material: ev.box.material,
				position: ev.position,
				show: ev.show,
				availability: ev.availability
			  }">
	</ac-box-desc>
</ac-layer>

JS:
			

                        var interval = new Cesium.TimeInterval({
				start: Cesium.JulianDate.fromDate(new Date()),
				stop: Cesium.JulianDate.fromDate(new Date(2017, 11, 13))
			});
			var arr = [interval];
			var timeint = new Cesium.TimeIntervalCollection(arr);
			var blueBox = new AcEntity({
				name: 'Blue box',
				position: Cesium.Cartesian3.fromDegrees(-114.0, 40.0, 300000.0),
				box: {
					dimensions: new Cesium.Cartesian3(400000.0, 300000.0, 500000.0),
					material: Cesium.Color.BLUE
				},
				availability: timeint
			});
			let notif: AcNotification = {
				id: event.id,
				entity: blueBox,
				actionType: ActionType.ADD_UPDATE
			}
			this.eventsCesium.next(notif);

**How to fix the issue:**
angular-cesium/src/angular-cesium/services/drawers/entities-drawer/entities-drawer.service.ts
after line 67 add
availability: cesiumProps.availability !== undefined ? cesiumProps.availability : undefined

after line 85 add
entity.availability = cesiumProps.availability !== undefined ? cesiumProps.availability : undefined;
        

**Version**
- angular-cesium@0.0.39

**Comment by tomermoshe** [comment]
Can you open a PR for it?

**Comment by zbennett10** [comment]
I am going to submit a PR for this one

**Comment by zbennett10** [comment]
We can close this one once the new version gets published! :)
