### ISSUE TITLE
Props assign of non-cesium properties - won't work on add, only on update.

### ISSUE THREAD

**Issue by davids868** [articodeltd/angular-cesium#188]
**Intended outcome:**
I tried to set a non-cesium property to an Angular Cesium component.
E.g: `<ac-billboard-desc props="{position: Position, aProperty: true}">`
As you can see, aProperty is not a cesium property, although I would like it to be part of the cesium entity just like your acEntity property. It doesn't work on ActionType.ADD_UPDATE - as an **ADD**.
When using ActionType.ADD_UPDATE - as an **UPDATE**,  It actually binds the non-cesium property to the entity.

**Actual outcome:**
When using ActionType.ADD_UPDATE - as an **ADD**,  the non-cesium property is not assigned to the Cesium entity.

**How to reproduce the issue:**
Use a billboard for example, assign to it a non-cesium property when you **ADD** it. DON'T update yet.
Try picking the object with your events picker and watch the entity's non-cesium property missing

**Version**
- angular-cesium@latest

**Comment by eitanfr** [comment]
The issue seems to be inactive. closed.
