### ISSUE TITLE
avoiding cesium breakdown workaround - an Idea

### ISSUE THREAD

**Issue by IOZD** [articodeltd/angular-cesium#196]
**Intended outcome:**
providing less than three points to polylgon or less than two points to polyline wont be a problem

**Actual outcome:**
when you pass a polygon with less than three points or a polyline with less than one - there is a Cesium Error that pops out and crashing the cesium map.

**How to reproduce the issue:**
pass manually a polygon with less than three points or polyline with less then one.

**idea for solution**
  - when there less than three points in polygon or less than two in polyline respectively,
 or initiate automatically a dispose function

**Version**
- angular-cesium@all versions

**Comment by eitanfr** [comment]
User responsibility for providing valid data for polygons and polylines
