### ISSUE TITLE
RnB - add doubleClick event on polyline editor 

### ISSUE THREAD

**Issue by IOZD** [articodeltd/angular-cesium#201]
**Intended outcome:**

when polyline editor/ RnB are in editing mode, I want to be able to create a functionality when double clicked

**Actual outcome:**

the is no triggered event when polyline editor is on or when RnB is in edit mode

**Version**
- angular-cesium@<version number>

**Comment by eitanfr** [comment]
Hi, 
can be done by using the [`MapEeventManager`](https://docs.angular-cesium.com/guides/map-events), plus check if the picked entity is the RNB polyline (has id the starts with `edit-polyline*`)
