### ISSUE TITLE
plonter position bug + disposing bug

### ISSUE THREAD

**Issue by IOZD** [articodeltd/angular-cesium#209]
**Intended outcome:**
1) pressing on entities triggering a plonter will open the plonter in the position that was pressed with the pointer. 
2) another thing, after the plonter is shown and I click somwhere else, the plonter should be disposed.

**Actual outcome:**
1) when the ac-map is in an inner component that is shifted right when clicking on the mouse the plonter opens right to the clicking position

![shifted_plonter](https://user-images.githubusercontent.com/21291245/34991072-fa3f8554-fad0-11e7-8def-6c68fcc817f7.png)

2)  after the plonter is shown and I click somwhere else , the plonter stays 

**Version**
- angular-cesium@<version number>

**Comment by eitanfr** [comment]
Old issue, 
Seems like a bug with the viewer CSS, check how to define the CSS here: https://docs.angular-cesium.com/getting-started/installation
closing
