### ISSUE TITLE
Wrapping angular-cesium components in custom components

### ISSUE THREAD

**Issue by jkabigting3** [articodeltd/angular-cesium#220]
I am trying to wrap the `ac-map` and `ac-billboard` components inside of their own custom components. I intend to have some logic that determines what graphic to use for the `ac-billboard` inside of the custom component.

**my-map**: Component used to wrap `ac-map`

Template: 
```html
<ac-map id="myMap">
    <ng-content></ng-content>
</ac-map>
```

**my-billboard**: Component used to wrap `ac-billboard`. Intended to generate an icon based on some data.

Template:
```html
<ac-billboard></ac-billboard>
```

These 2 components are part of the same module `my-cesium.module`:

```typescript
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { AngularCesiumModule } from 'angular-cesium';

import { MyMapComponent } from './my-map/my-map.component';
import { MyBillboardComponent } from './my-billboard/my-billboard.component';

@NgModule({
  imports: [
    CommonModule,
    AngularCesiumModule.forRoot()
  ],
  declarations: [MyMapComponent, MyBillboardComponent],
  exports: [MyMapComponent,MyBillboardComponent]
})
export class MyCesiumModule { }
```

I'm using the 2 custom components in my application's `app.component.html` like so:
```html
<app-my-map>
    <app-my-billboard></app-my-billboard>
</app-my-map>
```

**Intended outcome:**
Display an `ac-billboard` component on the `ac-map` using custom components that wrap `ac-map` and `ac-billboard`.

**Actual outcome:**
```javascript
MyBillboardComponent.html:1 ERROR Error: StaticInjectorError(AppModule)[AcBillboardComponent -> BillboardDrawerService]: 
  StaticInjectorError(Platform: core)[AcBillboardComponent -> BillboardDrawerService]: 
    NullInjectorError: No provider for BillboardDrawerService!
    at _NullInjector.get (core.js:1002)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1242)
    at StaticInjector.get (core.js:1110)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1242)
    at StaticInjector.get (core.js:1110)
    at resolveNgModuleDep (core.js:10854)
    at NgModuleRef_.get (core.js:12087)
    at resolveDep (core.js:12577)
```

I tried importing the BillboardDrawerService in `my-billboard.component.ts`, listing it as a provider and as an argument to the constructor. This leads to the same error, but for `No provider for CesiumService`. When I continue importing and declaring the providers for the errors that come up, it eventually circles back to the same one about `BillboardDrawerService`.

I noticed in the demo app, you wrap `ac-layer` in the `tracks-layer` component and have no issues doing so. Is there something I'm missing for my use case?

**How to reproduce the issue:**

I have put up a simple project generated from the Angular CLI that shows this issue:
```bash
git clone https://github.com/jkabigting3/ui-test.git
cd ui-test
npm install
ng serve
```

Open browser to localhost:4200

--

Alternatively, you can reproduce the issue with the following:

Create a `my-cesium` module that imports `AngularCesiumModule`.

Create 2 components (`my-map` and `my-billboard`) using the templates above.

Import `MyCesiumModule` in your app's root module and use the custom components in your app's template:

```html
<app-my-map>
    <app-my-billboard></app-my-billboard>
</app-my-map>
```

**Version**
- angular-cesium@0.0.48

**Comment by eitanfr** [comment]
checkout the docs for more info about getting started: https://docs.angular-cesium.com/core-concepts/the-basics
closing...

**Comment by edingeldein0616** [comment]
Not only did it take over 2 years to respond to this person, but that was the most unhelpful closure I've seen on GitHub. I don't see anything in the documentation about content projection.
