### ISSUE TITLE
Angular-Cesium Errror:

### ISSUE THREAD

**Issue by chiliblast** [articodeltd/angular-cesium#244]
Hello,

I am following the help https://www.npmjs.com/package/angular-cesium

The moment I installed cesium : npm install --save cesium

Now I am getting the following error when I run ‘ng serve’:

 

ERROR in Metadata version mismatch for module E:/angular-cesium-draw/node_modules/angular-cesium/index.d.ts, found version 4, expected 3, resolving symbol AppModule in E:/angular-cesium-draw/src/app/app.module.ts, resolving symbol AppModule in E:/angular-cesium-draw/src/app/app.module.ts, resolving symbol AppModule in E:/angular-cesium-draw/src/app/app.module.ts

 

Please help me with that.

Thanks

**Comment by eitanfr** [comment]
Can you please show your package.json file?

**Comment by chiliblast** [comment]
I installed angular cli. And now when I run Ng new myapp.  It doesn't work.

**Comment by eitanfr** [comment]
I want to see what are the dependencies your are working with in order to reproduce the error... Can you please attach your package.json

**Comment by tomermoshe** [comment]
closed because of inactivity,
If you are still having issues reopen the issue.
