### ISSUE TITLE
No regular rectangle component

### ISSUE THREAD

**Issue by Nirco96** [articodeltd/angular-cesium#254]
Hey, there is no implementation for a regular rectangle, the only rect that exists is a rectangle-desc whch doesn't work outside of an ac-layer. Is there a reason for that or was it just never implemented?

**Comment by tomermoshe** [comment]
Actually no,
Hopefully we will add it soon. 
You are welcomed to open a PR for it :)

**Comment by zbennett10** [comment]
I'm going to try to submit a PR for this one in the coming months!

**Comment by eitanfr** [comment]
added by the community PR.
thx @zbennett10
