### ISSUE TITLE
zoomToRectangle - service is zooming without dragging

### ISSUE THREAD

**Issue by alon6699** [articodeltd/angular-cesium#256]
When preforming **zoomToRectangle.activate** method and clicking on the map **without** dragging, the service makes an unpredictable behavior :
1. Sometimes it zooms to a random location in map. 
2. Sometimes the service is max zooming to the cursor's current location over the map
3. Sometimes it doesn't do anything at all - **that is the desired behavior**

Please assist and stabilize this service.

**Comment by tomermoshe** [comment]
Thanks for submitting the issue, we will check it.

**Comment by tomermoshe** [comment]
Solved in master branch - next release will be out very soon :)
