### ISSUE TITLE
zoomToRectangle - add optional cameraFlyTo options

### ISSUE THREAD

**Issue by alon6699** [articodeltd/angular-cesium#257]
When performing zoomToRectangle.activate and zooming, the camera automatically rotate to initial rotation because of activating cameraFlyTo method. 
Please add relevant parameters to the 'options' param inside the activate method, in order to allow control camera behavior.

**Comment by tomermoshe** [comment]
Thanks for submitting the issue, we will try to add it soon

**Comment by tomermoshe** [comment]
Solved in master branch - next release will be out very soon :)
