### ISSUE TITLE
[HELP] Fork the project

### ISSUE THREAD

**Issue by Crocsx** [articodeltd/angular-cesium#266]
Hello, I am sorry if it's not a request or a PR. 

I would like to Fork your project and modify some stuff in order to suit the need of my app. most of my changes are not suitable for PR I think that is why I would like to do this.

The problem is, I forked the project, and I do not understand how you build the package during the npm install. I tried to run  "prepare: npm run lib:build" but I get the following 

Project 'angular-cesium;' does not support the 'build' target.

If you could just explain quickly a way to build from the npm install, I would be grateful. thanks

**Comment by eitanfr** [comment]
Hi,
run `yarn lib:start` to compile angular-cesium lib in watch mode
and then run `yarn demo:start` to run the demo -> the demo will use the angular-cesium lib that the previous command created. 

run `yarn lib:build` to build the angular-cesium lib.

**Comment by Crocsx** [comment]
Thanks, I found out and forgot to close this ticket.
