### ISSUE TITLE
[feature idea]: Schematics support

### ISSUE THREAD

**Issue by bampakoa** [articodeltd/angular-cesium#267]
It would be nice if the library included Angular schematics for installing it in an Angular existing project. For example the corresponding `ng add...` command could:

1. Add the `AngularCesiumModule` to the app root module.
2. Add cesium related assets to the `angular.json` file.
3. Add `CESIUM_BASE_URL` in `main.ts` file.

to eliminate boilerplate. It could also be later extended for `ng generate...` commands to generate angular-cesium related components.

What do you think? I could definitely help on that.

Thanks!

**Comment by eitanfr** [comment]
Hi,
Great Idea!

Hope we will manage to add it soon.
Of course, PRs are welcomed :)

**Comment by bampakoa** [comment]
hey @eitanfr . Just to let you know that I am currently working to submit a PR for this hopefully, next week.
