### ISSUE TITLE
PolylineEditService - immediate double click behavoir

### ISSUE THREAD

**Issue by alon6699** [articodeltd/angular-cesium#271]
In polyline creation, immediate double click fires stop drawing action while the drawing is not a polyline. Please fix this so user can keep drawing.

**Comment by eitanfr** [comment]
Hi, 
I am not sure what is your problem, can you follow the issue guidelines and elaborate on  the current behavior and the expected behavior, angular-cesium version...

any way `polylineEditor.create()` accepts configuration for setting the event for finish drawing
