### ISSUE TITLE
Types to Cesium and Angular-Cesium

### ISSUE THREAD

**Issue by alon6699** [articodeltd/angular-cesium#274]
Please add more types to Angular-Cesium properties and Cesium.
Please don't use any as a type if its possible.

**Comment by eitanfr** [comment]
Thx,
we will try to add as we can, 
Also, we always welcome PRs if you wanna helping us with adding the types

**Comment by hodbauer** [comment]
There is [@types/cesium](https://www.npmjs.com/package/@types/cesium).
If this will added as a dependencies (or devDependencies - I don't sure which case is the correct here) to `angular-cesium` then some of the code here could be deleted and it will be easier to remove a lot of `any`.

**Comment by alon6699** [comment]
Thank you
