### ISSUE TITLE
Question : Cesium Map Configuration 

### ISSUE THREAD

**Issue by WebStew** [articodeltd/angular-cesium#276]
Apologies for posting an issue but I have been unable to find any documentation or examples on how to configure the Angular Cesium Map with the configuration options Cesium supports on https://cesiumjs.org/Cesium/Build/Documentation/Viewer.html.

I tried to pass a configuration option to .forRoot () and providing a ANGULAR_CESIUM_CONFIGURATION injection token useValue with no success.

Could anyone point me in the right direction?

**Comment by Crocsx** [comment]
It is shown in the demo examples available on the repo.

Anyway, here from my project ->

export class MyComponentContainingTheMap {
constructor(protected viewerConf: ViewerConfiguration){
this.viewerConf.viewerOptions {
 // blablabla
}
}

**Comment by WebStew** [comment]
I must be blind - thank you very much @Crocsx
