### ISSUE TITLE
upgrade Cesium 1.57.0 version,make a renderring error

### ISSUE THREAD

**Issue by VINOlive** [articodeltd/angular-cesium#277]
When Upgrade Cesium to 1.57.0 version
Add 3d tiles and toggle it
**The error is follow**
```
An error occurred while rendering. Rendering has stopped.
RuntimeError: Operator "/" requires vector or number arguments of matching types, or a number as the second argument. Arguments are undefined and 10000.
```
**Version**

- angular-cesium@0.039
- cesium@1.57.0

any help thank you

**Comment by eitanfr** [comment]
Thx for the issue,
I will check

**Comment by eitanfr** [comment]
Hi!
I tested with `1.58.1` and it works. 
please try with `1.58.1`, if the error is solved then reopen the issue.
