### ISSUE TITLE
MapsManagerService getMap() returns undefined in lazy loaded module

### ISSUE THREAD

**Issue by fidke** [articodeltd/angular-cesium#280]
**Intended outcome:**

`MapsManagerService` is intended to be a singleton service that allows retrieval of maps in components outside of `ac-map`. Calling `getMap()` should return the first map.

**Actual outcome:**

Calling `MapsManagerService.getMap()` from a component in a lazy loaded module returns `undefined`. Tested calling `getMap()` in both `ngOnInit()` and `ngAfterViewInit()`, both return `undefined`.

**How to reproduce the issue:**

I think this is because lazy loaded modules have their own injector. Because the lazy loaded module has it's own injector, a component in the lazy loaded module will get a different instance of `MapsManagerService` and it will not be a singleton. 

`ac-map` will be registered with one instance of `MapsManagerService` and the component in a lazy loaded module with get a different instance so when you call `getMap()` it'll return `undefined`.

Please see:
https://angular.io/guide/providers#limiting-provider-scope-by-lazy-loading-modules
https://angular.io/guide/sharing-ngmodules#using-components-vs-services-from-other-modules
https://angular.io/guide/singleton-services
https://stackoverflow.com/questions/39672816/can-lazy-loaded-modules-share-the-same-instance-of-a-service-provided-by-their-p?rq=1

I think if the `AngularCesiumModule` `providers` are moved to `forRoot` then it should work:
```
@NgModule({
  imports: [...],
  declarations: [...],
  exports: [...],
  providers: [JsonMapper, CesiumProperties, GeoUtilsService, ViewerFactory, MapsManagerService, ConfigurationService],
})
export class AngularCesiumModule {
static forRoot(config?: ModuleConfiguration): ModuleWithProviders {
    return {
      ngModule: AngularCesiumModule,
      providers: [
        {provide: ANGULAR_CESIUM_CONFIG, useValue: config},
        {provide: PIPES_CONFIG, multi: true, useValue: config && config.customPipes || []},
        {provide: PIPES_CONFIG, multi: true, useValue: PARSE_PIPES_CONFIG_MAP},
      ],
    };
  }
}
```
to:
```
@NgModule({
  imports: [...],
  declarations: [...],
  exports: [...],
})
export class AngularCesiumModule {
static forRoot(config?: ModuleConfiguration): ModuleWithProviders {
    return {
      ngModule: AngularCesiumModule,
      providers: [
        {provide: ANGULAR_CESIUM_CONFIG, useValue: config},
        {provide: PIPES_CONFIG, multi: true, useValue: config && config.customPipes || []},
        {provide: PIPES_CONFIG, multi: true, useValue: PARSE_PIPES_CONFIG_MAP},
        JsonMapper, CesiumProperties, GeoUtilsService, ViewerFactory, MapsManagerService, ConfigurationService
      ],
    };
  }
}
```

I tried to use the workaround of creating my own module like these examples:
https://stackoverflow.com/questions/39010654/angular-2-how-to-make-singleton-service-available-to-lazy-loaded-modules
and here:
https://github.com/angular/components/issues/1071

but I couldn't get it to work because I couldn't import `AcModelDescComponent`, `AcContextMenuWrapperComponent`, `AcPointPrimitiveDescComponent` and `AcCzmlDescComponent` from `'angular-cesium'`. (not sure if that's intentional?)

**Version**
- angular-cesium@0.0.56

**Comment by eitanfr** [comment]
Hi, thx for the issue. 
yes, you are right about the reason is related to angular DI and lazy loading modules. 

we will try to push a fix in our next release. 
meanwhile, you can try declaring AngularCesiumModule in the root app.module.
