### ISSUE TITLE
Editing polygons while creating it

### ISSUE THREAD

**Issue by alon6699** [articodeltd/angular-cesium#281]
Hi,
I want to edit a polygon/polyline both by creating an entity on the map and by editing it manually (like from the store). Is it possible to do both at the same time? In other words, is there a way to make it possible?

**Comment by Crocsx** [comment]
I don't exactly understand the question, all your Issues are like 3 unclear lines. this is not really a forum...

But...

It s really up to you how you handle your acEntity, if your question is, can I make a polygon (and his polyline) move by the user, and update the drawing by using store value, yes it is possible, but it is not built in in the library,  you need to make it manually.

**Comment by alon6699** [comment]
Hi, I'll try to make my question clearer.
Right now I need first to create the polygon and only then I will have the option to edit it.
I want to be able to edit the polygon properties in the process of creating it, and not having to wait for  the creation to be completed. 
For example, changing a point location/color of the filling/type of border-lining while I'm still in the process of creating the polygon and not having to complete the polygon creation and only then edit those properties.
Is it possible? If so, could you add the implementation to Angular-Cesium?

**Comment by eitanfr** [comment]
Hi,
the polygon editor has to options:
1. `polygonEditor.create()` - will create the polygon according to the user clicks.
2. `polygonEditor.edit(points,options)` - will create a polygon according to then given points then the polygon will be editable.

the api supports manipulating the polygon manually, can be done with the object returned from the editor:    
```
const polygon$ = polygonEditor.edit(); // or create()
polygon$.setManually(points,options);
```
look at `polygons-editor-layer.component` in the demo for example. 

Of course, we always welcome PRs if want to add more features to current API.

**Comment by alon6699** [comment]
Right now the function setManually only works if its in edit mode (all polygon points were created)
Can you implement a way to use the function **while in creation mode**?

**Comment by eitanfr** [comment]
I will put it in our roadmap.
but as I said Prs are welcomed :)

**Comment by eitanfr** [comment]
Hi, 
Now all editors use callback properties for the positions, 
so you can update the position in create mode:
```
const points = activeEditor.getCurrentPoints();
const lastPoint = points[points.length - 1];
lastPoint.setPosition( // your new position);
```
