### ISSUE TITLE
Fullscreen mode brings whole page to fullscreen

### ISSUE THREAD

**Issue by Rexam14** [articodeltd/angular-cesium#282]
**Issue description**
I'm integrating the Cesium Viewer in multiple pages of an Angular project. I defined a directive in which the Cesium viewer is initialized, so that I can use it in multiple parts of my code, behaving the same every time. For every viewer however, when pressing the fullscreen button on the Cesium viewer, the entire page is brought up fullscreen, not Cesium.  The result is a black background and the entire webpage in fullscreen. The problem is described also in  #158  where a standard solution is not provided. At the moment, when initializing the viewer in the `ngOnInit` function, I fixed the issue by adding an additional listener which toggle the fullscreen mode as follows:
```    
viewer.fullscreenButton.viewModel.command.afterExecute.addEventListener(function() {
      const canvas = viewer.canvas;
      if ('webkitRequestFullscreen' in canvas) {
        // chrome
        canvas.webkitRequestFullscreen();
      } else if ('requestFullScreen' in canvas) {
        // other browsers
          canvas.requestFullScreen();
      }
});
```
There are two downsides of this approach:
1. Only the canvas is brought fullscreen and the widget are all lost.
2. The only way for quitting fullscreen is by pressing the ESC button on the keyboard. When doing so, the fullscreen button on the Cesium changes its icon, looking like the following:
![button](https://user-images.githubusercontent.com/9914964/60578429-77565780-9d81-11e9-8ece-1d993c5b4b5c.png)
So it seems that Cesium believes it's still in fullscreen mode. If I try to press it again, I'm going fullscreen and can press again the ESC button to exit fullscreen. The button on Cesium stays the same as shown in the image above and cannot be brought back ever to the original icon (which I insert in the following for documenting purposes):
![original](https://user-images.githubusercontent.com/9914964/60579114-bfc24500-9d82-11e9-9e09-7f08d97bbdc0.png)

Is there any existing solution to this issue at the moment?

**Version**
- angular-cesium@1.58.1

**Comment by eitanfr** [comment]
The only thing I can think of is implementing the full-screen functionality by yourself and not using cesium's widget 

check out [geo-strike](https://geo-strike.now.sh/), here we did manual full-screen request for the entire document. [the code](https://github.com/Webiks/GeoStrike/blob/master/packages/client/src/app/game/views/game-container/game-toolbar/game-toolbar.component.ts#L58).

**Comment by Rexam14** [comment]
Hi there again. I found a solution to fix this problem for my case. I'm posting the solution here for posterity, but it would be good to fix this behavior in a future release.
Basically, I created a fullscreen handler function with tests if a certain css class is applied to Cesium (at load, it is applied by default). If it is, the class is removed and vice versa:

```
  fullscreenHandler(event: any) {
    if (document.getElementById('fullscreenMdCesium').classList.contains('fullscreenMdCesium')) {
      document.getElementById('fullscreenMdCesium').classList.remove('fullscreenMdCesium');
    } else {
      document.getElementById('fullscreenMdCesium').classList.add('fullscreenMdCesium');
    }
  }
```

Then I override the fullscreen button via the following command:

```
document.addEventListener(Cesium.Fullscreen.changeEventName, this.fullscreenHandler);
``` 

The css class is what provides the fullscreen to stretch well, keeping the widgets, the bottom bar and all the rest at their place, and it looks like this:

```
::ng-deep .fullscreenModeCesium {
  height: 100vh !important;
  width: 100vw !important;
  position: fixed;
  z-index: 9999;
  top: 0;
  left: 0;
}
```
