### ISSUE TITLE
picking entities configuration in EventRegistrationInput interface

### ISSUE THREAD

**Issue by alon6699** [articodeltd/angular-cesium#294]
When we want to pick an entity on the map in Cesium (pick/drillpick) the target is defined by a 3X3 default rectangle if size was not received.
Could you please add a configuration to the size of the rectangle.
I'd like the configuration to be available from EventRegistrationInput interface.

**Comment by eitanfr** [comment]
Hi, 
hope we will get there soon.
If you could open us a PR with the wanted change it could be much faster, I will be happy to guide you in the process.

**Comment by eitanfr** [comment]
implemented!
