### ISSUE TITLE
PolygonsEditorService error on Cesium 1.60

### ISSUE THREAD

**Issue by shaharido1** [articodeltd/angular-cesium#295]
Hey, 

Angaulr-cesium version: 0.0.55
cesium version: 1.59 -> 1.60

there seem to be breaking change in Cesium 1.60 which cause error on the feature PolygonsEditorService.

While everything worked fine in 1.59; upgrading cesium to 1.60 cause drawing polygon to error (general unspecified cesium error : "length of array of undefined..")

**Comment by eitanfr** [comment]
Hi, can you please explain how to reproduce the error?
as far as I tested all works, the demo uses cesium 1.60 - http://www.angular-cesium.com/

**Comment by shaharido1** [comment]
Hey, 

I upgraded angualr-cesium and it seem to resolve it. 
it was broken on angular-cesium: 0.0.55. but seem ok on  0.0.59.

**Comment by eitanfr** [comment]
Thx for your replay
