### ISSUE TITLE
Constantly calling updateLayer for <ac-layer> crashes viewer

### ISSUE THREAD

**Issue by devinnoth** [articodeltd/angular-cesium#296]
Hello,

I'm running into an issue where having the updateLayer function for my <ac-layer> constantly called is crashing my viewer (it freezes on one frame, and becomes unable to interact with). The call I'm using to update the layer looks like this,
```this.orbitPathLayer.update( this.orbitPaths[ 'mms1' ], '1' );```
and this call lies inside an event listener. 

The event listener runs through the clock's onTick function, and looks like,
```
const viewer = this.cesiumService.getViewer();
const clock = viewer.clock;
let toInertial = new Cesium.Matrix3();
let rotatingOrbitPath = new Cesium.Matrix4();

clock.onTick.addEventListener( () => {
            if ( !Cesium.defined( Cesium.Transforms.computeIcrfToFixedMatrix( clock.currentTime, toInertial ))) {
                Cesium.Matrix3.IDENTITY.clone( toInertial )
            }
            rotatingOrbitPath = Cesium.Matrix4.fromRotationTranslation(
                toInertial,
                Cesium.Cartesian3.ZERO,
                rotatingOrbitPath
            );
            this.orbitPaths[ 'mms1' ] = {
                width: 1,
                positions: this.ephemerisDataService.positions[ 'mms1' ],
                material: Cesium.Color.LIGHTSTEELBLUE,
                modelMatrix: rotatingOrbitPath
            };
            this.orbitPathLayer.update( this.orbitPaths[ 'mms1' ], '1' );
        });
});
```

The point of this event listener is to create a geo-to-inertial matrix4 based on the specific cesium clock time to apply to an orbit path as to make it appear in an inertial reference frame. This value is then set to the  ```modelMatrix``` attribute of the polyline entity. For reference, this is the HTML I'm using to create my orbit path. 
```
<ac-layer #orbitPathLayer acFor="let orbitPath of orbitPaths$" [context]="this">
    <ac-polyline-desc props="{
          width: orbitPath.width,
          positions: orbitPath.positions,
          material: orbitPath.material,
          modelMatrix: orbitPath.modelMatrix
        }">
    </ac-polyline-desc>
</ac-layer>
```
Due to this, the call to update the orbit path (which is done by updating the layer itself) must lie in the event listener as it needs to be updated at every tick. 

Since calling the updateLayer function every tick seems to crash the viewer entirely, is there another way to update the layer constantly that would in theory not crash the viewer?

Is there also maybe a different way I should be attempting to put the orbitPath polyline into an inertial reference frame entirely?

Thanks in advance for the help.

**Version**
- angular-cesium@0.0.56

**Comment by eitanfr** [comment]
Hi, 
Seems more as cesium issue and not angular-cesium.
any way,
1. `modelMatrix` isnt a known attribute of polyline https://cesiumjs.org/Cesium/Build/Documentation/PolylineGraphics.html
2. if you want to do update in high rates for an entity prop, then check out cesium `callbackPropertiy` - https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Callback%20Property.html.

**Comment by devinnoth** [comment]
Thanks for the response, 

modelMatrix seems to be an attribute of Primitives, instead of polyline. 
[https://cesiumjs.org/Cesium/Build/Documentation/Primitive.html](https://cesiumjs.org/Cesium/Build/Documentation/Primitive.html)

Does this mean there is no way through angular-cesium calls itself to rotate an entity on a matrix4? As I'm assuming due to your answer the attributes defined in ```<ac-polyline-desc>``` or ```<ac-polyline-primitive-desc>``` for that matter won't support ```modelMatrix```. 

And in terms of the ```callbackProperty```, that looks all well and good but wouldn't that still create the same problem I had before? The callback property would change the value at a high rate, but I would still have to call ```orbitPathLayer.update()``` at the same rate, which would crash the app again? This callbackProperty seems to really only work if I add the primitive through cesium itself, rather than calling an angular-cesium HTML method like ```<ac-polyline-primitive-desc>```.

**Comment by eitanfr** [comment]
yes, creating Primitive isn't supported using an existing component,
`ac-polyline-desc` - wrapper for Entity and `PolylineGraphics`
`polyline-primitive-desc` - wrapper for primitive [Polyline](https://cesiumjs.org/Cesium/Build/Documentation/Polyline.html?classFilter=polyline)

about callback property, when you use callback property you dont need to call `update()`.
for example, if you have `position` as `callbackProperty` then you just need to change your entity position and cesium will the callbackProperty by himself to update to the new value

**Comment by eitanfr** [comment]
Stale issue... closing
