### ISSUE TITLE
Angular 7 support?

### ISSUE THREAD

**Issue by parky128** [articodeltd/angular-cesium#298]
I am following the Getting Started guide, and I am using the angular cli. On attempting to serve the project, I get the following error:

```
ERROR in ./node_modules/cesium/index.js 9:4
Module parse failed: 'return' outside of function (9:4)
You may need an appropriate loader to handle this file type.
| if (process.env.NODE_ENV === 'production') {
|     module.exports = require(path.join(__dirname, 'Build/Cesium/Cesium'));
>     return;
| }
|
ℹ ｢wdm｣: Failed to compile.
```

I am actually using angular 7, and notice that angular-cesium requires angular 8 to be installed, so I am assuming this could be the reason for my error. 

I have a sample repo at -> https://github.com/parky128/cesium-playground where you can replicate what I am seeing

Is there another version of angular-cesium I can use that will work with angular 7 or do you only support 8 as of now?

**Comment by TheTiGuR** [comment]
In your tsconfig.json, add a line in your paths section:

`"cesium": ["node_modules/cesium/Build/Cesium/Cesium.js"]`

**Comment by parky128** [comment]
Thanks @TheTiGuR 👍
