### ISSUE TITLE
Trouble getting @types/cesium to work correctly

### ISSUE THREAD

**Issue by parky128** [articodeltd/angular-cesium#300]
Having just followed the getting started guide, I now have a basic app running. However, even with `@types/cesium` installed, I cannot get any types to be picked up correctly.

For example in my `main.ts` I have

```
import * as Cesium from 'cesium';
Cesium.buildModuleUrl.setBaseUrl('/assets/cesium/');
```

But I get a warning for my import saying:

> Could not find a declaration file for module 'cesium'. '/Users/my-laptop/Documents/Github/my-app/node_modules/cesium/Build/Cesium/Cesium.js' implicitly has an 'any' type.

What could be the problem here?
Thanks

**Comment by popoleeMaster** [comment]
did you do 

```Add declare var Cesium; to typing.d.ts file (add the file to src directory).```

**Comment by eitanfr** [comment]
Stale issue closing...
