### ISSUE TITLE
Difficulties getting polylines to display with sample data

### ISSUE THREAD

**Issue by parky128** [articodeltd/angular-cesium#302]
I am trying out angular-cesium and cannot get polylines rendering in my application.

My component html is as follows:

    <ac-map>
      <ac-layer acFor="let path of paths$" [context]="this">
        <ac-polyline-desc props="{
            position: path.positions,
            width: path.width,
            material: path.material
        }">
        </ac-polyline-desc>
      </ac-layer>
    </ac-map>

And the ts source:

    import { Component, OnInit } from '@angular/core';
    import { AcNotification, ActionType } from 'angular-cesium';
    import { Observable, from } from 'rxjs';
    import {map} from 'rxjs/operators';
    
    @Component({
      selector: 'app-root',
      templateUrl: './app.component.html',
      styleUrls: ['./app.component.scss']
    })
    export class AppComponent implements OnInit {
      paths$: Observable<AcNotification>;
    
      ngOnInit() {
        const yellowMaterial = new Cesium.Material({
          fabric: {
            type: 'Color',
            uniforms: {
              color: new Cesium.Color(1.0, 1.0, 0.0, 1.0)
            }
          }
        });
    
        this.paths$ = from([
          {
            id: '1',
            width: 2,
            positions: Cesium.Cartesian3.fromDegreesArray(
              [
                -3.131172, 51.478424,
                18.492839, 51.649888
              ]),
            material: yellowMaterial
          }
        ]).pipe(
          map(path => ({
            id: path.id,
            actionType: ActionType.ADD_UPDATE,
            entity: path
          }))
        );
    
      }
    }

This is based on the 'planes' basic [example][1], which I can get to work just fine. So I must be doing something subtly wrong when trying to use the polyline variation with multiple points, or something else even more stupid?

Thanks 

  [1]: https://github.com/articodeltd/angular-cesium#basic-example

**Comment by eitanfr** [comment]
Hi,
check out our demo, clone the project and try to run our demo.
check out the [polyline example](https://github.com/articodeltd/angular-cesium/blob/master/demo/app/components/polyline-layer-example/polyline-layer-example.component.html):

**Comment by zcase** [comment]
I have looked at the demos and non of them seem to run. They just display the globe. Any updates on this issue?

**Comment by eitanfr** [comment]
Hi,

**Comment by zcase** [comment]
@eitanfr  So I re cloned the repo and got everything up and running.  The demos are working. However, the stackblitz demos don't seem to be working. I think my issue was I never updated my angular-cesium and cesium packages. Doing this now to confirm

**Comment by eitanfr** [comment]
@zcase I'm happy to hear that the demo worked. 
about stackblitz demo, I checked again and it works, https://angular-cesium-polyline-example.stackblitz.io. 

Closing the issue for now. if you have any more issues reopen the thread
