### ISSUE TITLE
ac-html always shown

### ISSUE THREAD

**Issue by popoleeMaster** [articodeltd/angular-cesium#305]
I have a simple layer inside my ac-map.

All layer with show works, but html is always displayed.

```
<ac-layer #menuLayer acFor="let menu of menu$" [context]="this">
  <ac-html-desc props="{
    position: menu.position,
    fillColor : labelParam.fillColor,
    show: false,
    horizontalOrigin : labelParam.horizontalOrigin,
    verticalOrigin : labelParam.verticalOrigin,
    scale: 0.1,
    pixelOffset : labelParam.pixelOffset,
  }">
    <ng-template let-html>
      My Div show is : {{ html.show }}
        <!-- <ndc-dynamic [ndcDynamicComponent]="type" [ndcDynamicInputs]="inputs"></ndc-dynamic> -->
    </ng-template>
  </ac-html-desc>
</ac-layer>
```

Result => Div is shown. 

https://prnt.sc/pem22r

I also tried using show from the Entity Directly, but same effect

**Comment by eitanfr** [comment]
looks like it related to #306, 
please check the demo, for [example](https://github.com/articodeltd/angular-cesium/blob/master/demo/app/components/html-layer/html-example.component.ts).
if you still have issues please reopen the issue and attach the component code too.
