### ISSUE TITLE
feature idea: AcLayer maintains components for selection

### ISSUE THREAD

**Issue by matttm** [articodeltd/angular-cesium#308]
I think the AcLayer should manage entity's properties differently. For example, when using the selection service, it adds or removes the 'selected' property appropriately; however if the entities on this layer are being updated by an Observable<AcNotification>, the fresh entities on that stream do not have this 'selected' property that was added to this entity's previous iteration. Hence, if an item is selected, once the layer is updated with the fresh iteration, the item will be, practically, in the unselected state. I think the selected property and possibly any dynamic properties should be managed in someway by AcLayerComponent. What do you think?

Also, a problem is that components cannot share an instance of a custom service that uses services from AcMapComponent. i.e. two components cannot not be notified when an entity is selected using SelectionManagerService because it has to be provided on a component basis.  So, a feature idea might be dynamic injection into AcMapComponent.

**Version**
- angular-cesium@0.60

**Comment by eitanfr** [comment]
Thx for the idea, 
First of all `SelectionManagerService` is provided by the user and not by the `AcMap` component, so you can provide it in the root module and access it from anywhere. 

`SelectionManagerService` is an opinioned way to implement selection - it adds `selected=true` property to the acEntity. 

About the issue with the selected state of the entity, I guess you use some kind of data store where you save your entities, but the entity in the store doesn't get updated with the selected state.
The recommended flow should be: you will subscribe to the selected entities observer `selectionService.selectedEntities$().subscribe()`, then update the entity in the store,  then the update in the store will propagate to the `ac-layer` and the map will rerender.

**Comment by matttm** [comment]
I don't believe the selection service can be provided into the root, as it needs a MapManager, which means that it has to be a child of the AcMapComponent, which provides the mapManager. I do like the preferred flow for selection you mentioned , thank you!!

**Comment by matttm** [comment]
I don't believe the selection service can be provided into the root, as it needs a MapManager, which means that it has to be a child of the AcMapComponent, because it provides the mapManager. I do like the preferred flow for selection you mentioned--thank you!!

**Comment by matttm** [comment]
I don't believe the selection service can be provided into the root, as it needs a MapManager, which means that it has to be a child of the AcMapComponent, because it provides the mapManager. I do like the preferred flow for selection you mentioned--thank you!!
