### ISSUE TITLE
Feature Idea - Point entity should be be able to support labels and other editor component features

### ISSUE THREAD

**Issue by anotherhale** [articodeltd/angular-cesium#320]
`Point` should be a geometry editor component similar to `polyline-editor.component.ts` so that it can support labels and other features that are supported by the editor components.

I suggest creating the following classes to support this:

Models:
`angular-cesium-widgets/models/editable-point.ts`
`angular-cesium-widgets/models/point-edit-options.ts`
`angular-cesium-widgets/models/point-edit-update.ts`
`angular-cesium-widgets/models/point-editor-observable.ts`

Components:
`angular-cesium-widgets/components/point-editor/point-editor.component.ts`

Services
`angular-cesium-widgets/services/entity-editors/point-editor/point-editor.service.ts`
`angular-cesium-widgets/services/entity-editors/point-editor/point-manager.service.ts`

I have already started on this and should have a PR open soon.

**Comment by eitanfr** [comment]
Hi,
Thx we happily accept PRs.
The file structure seems right, but notice some of the entities already exists (`edit-point.ts` and `PointProps` in `polyline-edit-options.ts`). 
Let us know if you need help :)

**Comment by anotherhale** [comment]
I created the point editor to display the point once the mouse drag event registers on the map. I think that this would also be a good feature for the other components (circle, polygon, etc).  See this demo for further example. I know that when I am drawing entities it is sometimes confusing to know if I already selected the draw feature or not.  This way you know that it is ready to be drawn to the screen as soon as you click.
https://youtu.be/reTXhCrFsRw

**Comment by eitanfr** [comment]
#322 looks good, merged!

**Comment by anotherhale** [comment]
I add the `point` draw icon to the toolbar component in the demo code.  I can also add it to the landing-page if you like.

**Comment by eitanfr** [comment]
Thx I noticed it.
will do later :)
