### ISSUE TITLE
Polygon/Polyline editor service with multi maps

### ISSUE THREAD

**Issue by rongoldinfeld** [articodeltd/angular-cesium#321]
**Intended outcome:**
Using any of the Polygon/PolylineEditorService with multiple maps, by providing the desired map Id, or deciding based on the first  click. 

**Actual outcome:**
Creating works only on the first map. 

**How to reproduce the issue:**
Create a map component and as a child a polyline-edit-layer. 
Now duplicate the map component, two polyline-editor-layer should be created. Now try to create a polyline on the other map. 

**Version**
- angular-cesium@0.0.54

**Comment by eitanfr** [comment]
Hi,
The polygon editor service works with the `<polygons-editor>`, so you need to put the `<polygons-editor>` in both of your `ac-map` components hierarchy,  and declare `PolygonEditorService ` for each of the map components. 
 Each `PolygonEditorService` will interact with his `<polygons-editor>`.

**Comment by rongoldinfeld** [comment]
That's exactly what I'm doing. But the drawing works only on one map and the polygon is drawn upon only one map.

**Comment by eitanfr** [comment]
Strange, 
Can you please add code samples?

**Comment by rongoldinfeld** [comment]
Okay, so I was missing the part of providing it for each of the components. Thanks :)
