### ISSUE TITLE
Material property in polylineProps interface won't accept Cesium.Material()

### ISSUE THREAD

**Issue by alon6699** [articodeltd/angular-cesium#329]
Hey, 
As you know, material property is a function that returns the material of polyline lines. 
In version 0.0.53 my code worked and I could draw a dashed polyline like that:
polylinesEditorService.create({
   polylineProps: {
     material: () => new Cesium.Materila({ fabric: { 
type: 'PolylineDash', uniforms: { dashPattern:'someDashPattern'}
})
}});

But after updating to the current library version its' not working anymore.

**Comment by eitanfr** [comment]
Hi,
you should use `PolylineDashedMaterialProperty`, like:
```
    const dashedMaterial = new Cesium.PolylineDashMaterialProperty({
      color: Cesium.Color.ORANGE,
    });
    this.editing$ = this.polylineEditor.create({
      polylineProps: {
        material: () => dashedMaterial,
      }
    });
```

**Comment by liorazroel** [comment]
i tried it on angular Cesium version  0.0.66 today and it doesn't work.
Cesium throws an error: "... rendering has stopped in e._uniform[a] is not a function..."
