### ISSUE TITLE
Disabling Shadows on model 

### ISSUE THREAD

**Issue by h11a** [articodeltd/angular-cesium#332]
**Intended outcome:**
I am trying to disable shadows for a model but when I import 'angular-cesium/lib/angular-cesium/cesium-enhancements/StaticGeometryColorBatch'  it only has 

```
/**
 * Fix for the constant entity shadowing.
 * PR in Cesium repo: https://github.com/AnalyticalGraphicsInc/cesium/pull/5736
 */
export declare function fixCesiumEntitiesShadows(): void;
``` 
I am trying to use ShadowMode from here 
https://articodeltd.github.io/angular-cesium/miscellaneous/variables.html

**Actual outcome:**
Am i doing this incorrectly? If so how could I disable shadows on my model. 

**Version**
- angular-cesium@0.0.64

**Comment by ErvanRenault-GE** [comment]
Hey ! 

I have the same problem on my project.

**Comment by eitanfr** [comment]
Hi, 
Check out the the `forRoot()` configuration for turning on and off shadow fix that angular-cesium applies: https://docs.angular-cesium.com/getting-started/installation#angularcesiummodule-configuration

 If it is a `<ac-model>` entity then just use the [shadows](https://cesium.com/docs/cesiumjs-ref-doc/ModelGraphics.html?classFilter=model) prop.

**Comment by h11a** [comment]
Thanks its working with the shadows prop. Am i able to reference the enum ShadowMode in typescript?

**Comment by eitanfr** [comment]
yes, just put it as a public class member
