### ISSUE TITLE
EllipseEditorObservable Disposing 

### ISSUE THREAD

**Issue by boyanstanchev** [articodeltd/angular-cesium#338]
Disposing of EllipseEditorObservable throws an error
 `Uncaught TypeError: Cannot read property 'dispose' of undefined` .

Go to https://stackblitz.com/edit/angular-cesium-ellipse-editor-example?embed=1&file=src/app/ellipse-editor-example/ellipse-eidtor-example.component.ts, create an ellipse a then click 'Stop Edit Ellipse' to reproduce.

**Comment by anotherhale** [comment]
Looks like it is crashing here:
https://github.com/articodeltd/angular-cesium/blob/2d451bdd328fcf81af7ff994847a8fffde17c96c/projects/angular-cesium/src/lib/angular-cesium-widgets/services/entity-editors/ellipses-editor/ellipses-editor.service.ts#L398
The `addSecondRadiusRegistration` is undefined on line 390 and then the observables map gets polluted with the undefined element. 
Hopefully with that info you can dig a little deeper into the problem.  If you need further help I can look into it more next week.

**Comment by anotherhale** [comment]
@boyanstanchev where you able to find a solution to this?  I can still assist further if you would like me to.

**Comment by boyanstanchev** [comment]
@anotherhale Thanks for the info, how can I test and debug this? I've forked and cloned the repository. It's my first time contributing to a project.

**Comment by boyanstanchev** [comment]
I think I found where the undefined is coming from https://github.com/articodeltd/angular-cesium/blob/2d451bdd328fcf81af7ff994847a8fffde17c96c/projects/angular-cesium/src/lib/angular-cesium-widgets/services/entity-editors/ellipses-editor/ellipses-editor.service.ts#L390. **addSecondRadiusRegistration** is always undefined and we have if statement checking that, so maybe `const observables = [pointDragRegistration]` will fix that?
