### ISSUE TITLE
Package does not support schematics

### ISSUE THREAD

**Issue by brianpboyd** [articodeltd/angular-cesium#339]
**Intended outcome:**

Install of angular-cesium into a new ng project
**Actual outcome:**

The following error is produced when running the `ng add angular-cesium`
The package you are trying to add does not support schemeatc
**How to reproduce the issue:**
 I have the current version on angular installed which is 9.0.4.  I am creating a new ng project and running the command `ng add angular-cesium` .  

**Version**
- angular-cesium@<version number>
N/A

**Comment by eitanfr** [comment]
Hi, Angular 9 still isn't supported. 
Currently working on adjusting the version

**Comment by eitanfr** [comment]
Fix in #341

**Comment by leo222222222** [comment]
Hey eitan ! I still have the issue today with the latest version of angular-cesium.


Here is my Angular version :
Angular CLI: 18.1.1
Node: 20.15.1
Package Manager: npm 10.7.0
OS: linux x64

Angular: 18.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.1
@angular-devkit/build-angular   18.1.1
@angular-devkit/core            18.1.1
@angular-devkit/schematics      18.1.1
@angular/language-service       <error>
@schematics/angular             18.1.1
ng-packagr                      <error>
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.8


An here are the inputs / output when I try to install angular-cesium :
leopold@leopold-Virtual-Machine:~/Documents/mygui$ ng add angular-cesium
✔ Determining Package Manager
  › Using package manager: npm
✔ Searching for compatible package version
  › Found compatible package version: angular-cesium@0.0.1.
✔ Loading package information from registry
✔ Confirming installation
✔ Installing package
Package "angular-cesium" was found but does not support schematics.


Any help would be very appreciated ! Thx !
