### ISSUE TITLE
Circle Editor dispose method throws exception (ver 0.66)

### ISSUE THREAD

**Issue by itzikntn** [articodeltd/angular-cesium#366]
when you call Circle Editor dispose method , you get an exception on getCenter of undefined
this happens only on version 0.66 (before that it was ok).

code for an example:
 private stopEdit() {
    this.editing$.dispose();  
    this.editing$ = null; 
  }

**Comment by bampakoa** [comment]
@itzikntn it looks like you have code that calls `this.editing$.getCenter()` when you try to dispose it. Is it some kind of timer that you use? BTW, I checked the demo in https://github.com/articodeltd/angular-cesium/tree/master/projects/demo/src/app/components/editor-layer/circles-editor-layer and it works correctly with 0.0.66 version

**Comment by itzikntn** [comment]
Hi ,

thank you for replay .

I think it was a problem with angular cesium package  on my node modules , I  reinstalled it on the problem solved. 

just for your information , you call get center on dispose (see attached images)

![image](https://user-images.githubusercontent.com/38310394/103735485-db04b500-4ff6-11eb-8c11-266945ec043b.png)

![image](https://user-images.githubusercontent.com/38310394/103735642-27e88b80-4ff7-11eb-9ad4-711b7667280b.png)

Best Regards
Itzhak Natan

**Comment by bampakoa** [comment]
Thanks for the feedback @itzikntn 👍. I assume this issue can be closed now right?

**Comment by itzikntn** [comment]
yes 
10x

**Comment by bampakoa** [comment]
I cannot close it, so feel free to do it yourself. I am glad you find a solution after all 😊
