### ISSUE TITLE
Release plans for version 1.0.0

### ISSUE THREAD

**Issue by bampakoa** [articodeltd/angular-cesium#367]
Hello all,

I am following the library for some years now and I have noticed that version 1 has not been released. Even if it is production ready packed with a lot of useful features, contains a decent documentation and the maintainers have done a great job supporting it, I have seen that only the patch version is modified across releases.
Is this something intended? As an Angular and Cesium developer, I have the feeling that many other users are discouraged from using the library even if it is so cool because they think that it is not ready for production.

Thanks

**Comment by Crocsx** [comment]
To me it looks like this library as been abandoned for more than half a year now. Which is a bit scary cause cesium keep improving but we are stagnating here. 

There was a lot of activity a while back, and hope it's just a temporary situation ^^

**Comment by eitanfr** [comment]
Hi, 
Indeed work on the project has slow down, we have been busy in recent months...
but PRs and updates are always welcomed :)

About the versioning, actually a good point maybe it is time to change it to version 1.0.0

**Comment by bampakoa** [comment]
Thanks for your answer @eitanfr 🙏
