### ISSUE TITLE
Will this project be continued?

### ISSUE THREAD

**Issue by CodeCakePie** [articodeltd/angular-cesium#372]
Hello everybody,

I'm currently working on an angular project where i need cesium for 3d terrain. I think that it is quite a pain to implement cesium in angular the standard way and so I found this project.

But as far as I see, it's quite dead... Are there any plans to update to angular 11 or anything?

**Comment by aznguy** [comment]
Ah yes, I'm very interested in this as well. Nothing much has been happening lately unfortunately. I hope to see some liveliness in this project soon again

**Comment by ramtob** [comment]
Hello,
I am currently upgrading angular-cesium to Angular 11.
Opened issue #374 PR #373

**Comment by CodeCakePie** [comment]
That is great news, I will keep an eye on it.

Thank you!

**Comment by eitanfr** [comment]
Thx to @ramtob for upgrading to angular 11.
closing...
