### ISSUE TITLE
A compilation error in demo

### ISSUE THREAD

**Issue by ramtob** [articodeltd/angular-cesium#377]
**Intended outcome:**
The demo application will compile and run successfully 

**Actual outcome:**
Getting an error message:  
`An unhandled exception occurred: Script file ./node_modules/socket.io-client/dist/socket.io.js does not exist.`

**How to reproduce the issue:**
Run `yarn run demo:start`

**Version**
- angular-cesium@0.0.67

**Comment by eitanfr** [comment]
fixed
